# 应用服务 WEB 访问端口
server:
  port: 8016
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/xianyu?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
   driver-class-name: com.mysql.cj.jdbc.Driver
   username: root
   password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 设置最大上传文件大小 (单位为字节)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: file:E:\
upload:
  path: E:\test\
  Imagepath: E:\test\image\
dromara:
  x-file-storage: #文件存储配置
    default-platform: aliyun-oss-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    #对应平台的配置写在这里，注意缩进要对齐
    aliyun-oss:
      - platform:  # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: 
        secret-key: 
        end-point: 
        bucket-name: 
        domain:  # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path:  # 基础路径





